package com.forkexec.rst.ws.cli;

import static javax.xml.ws.BindingProvider.ENDPOINT_ADDRESS_PROPERTY;

import java.util.List;
import java.util.Map;

import javax.xml.ws.BindingProvider;

import com.forkexec.rst.ws.*;

import pt.ulisboa.tecnico.sdis.ws.uddi.UDDINaming;

/**
 * Client port wrapper.
 *
 * Adds easier end point address configuration to the Port generated by
 * wsimport.
 */
public class RestaurantClient implements RestaurantPortType {

	/** WS service */
	RestaurantService service = null;

	/** WS port (port type is the interface, port is the implementation) */
	RestaurantPortType port = null;

	/** UDDI server URL */
	private String uddiURL = null;

	/** WS name */
	private String wsName = null;

	/** WS end point address */
	private String wsURL = null; // default value is defined inside WSDL

	public String getWsURL() {
		return wsURL;
	}

	/** output option **/
	private boolean verbose = false;

	public boolean isVerbose() {
		return verbose;
	}

	public void setVerbose(boolean verbose) {
		this.verbose = verbose;
	}

	/** constructor with provided web service URL */
	public RestaurantClient(String wsURL) throws RestaurantClientException {
		this.wsURL = wsURL;
		createStub();
	}

	/** constructor with provided UDDI location and name */
	public RestaurantClient(String uddiURL, String wsName) throws RestaurantClientException {
		this.uddiURL = uddiURL;
		this.wsName = wsName;
		uddiLookup();
		createStub();
	}

	/** UDDI lookup */
	private void uddiLookup() throws RestaurantClientException {
		try {
			if (verbose)
				System.out.printf("Contacting UDDI at %s%n", uddiURL);
			UDDINaming uddiNaming = new UDDINaming(uddiURL);

			if (verbose)
				System.out.printf("Looking for '%s'%n", wsName);
			wsURL = uddiNaming.lookup(wsName);

		} catch (Exception e) {
			String msg = String.format("Client failed lookup on UDDI at %s!", uddiURL);
			throw new RestaurantClientException(msg, e);
		}

		if (wsURL == null) {
			String msg = String.format("Service with name %s not found on UDDI at %s", wsName, uddiURL);
			throw new RestaurantClientException(msg);
		}
	}

	/** Stub creation and configuration */
	private void createStub() {
		if (verbose)
			System.out.println("Creating stub ...");
		service = new RestaurantService();
		port = service.getRestaurantPort();

		if (wsURL != null) {
			if (verbose)
				System.out.println("Setting endpoint address ...");
			BindingProvider bindingProvider = (BindingProvider) port;
			Map<String, Object> requestContext = bindingProvider.getRequestContext();
			requestContext.put(ENDPOINT_ADDRESS_PROPERTY, wsURL);
		}
	}

	// remote invocation methods ----------------------------------------------


	@Override
	public MenuOrder orderMenu(MenuId arg0, int arg1)
			throws BadMenuIdFault_Exception, BadQuantityFault_Exception, InsufficientQuantityFault_Exception {
		return port.orderMenu(arg0, arg1);
	}

	@Override
	public List<Menu> searchMenus(String descriptionText) throws BadTextFault_Exception {
		return port.searchMenus(descriptionText);
	}

	@Override
	public Menu getMenu(MenuId menuId) throws BadMenuIdFault_Exception {
		return port.getMenu(menuId);
	}
	
	
	
	// control operations -----------------------------------------------------

	@Override
	public String ctrlPing(String inputMessage) {
		return port.ctrlPing(inputMessage);
	}

	@Override
	public void ctrlClear() {
		port.ctrlClear();
	}

	@Override
	public void ctrlInit(List<MenuInit> initialMenus) throws BadInitFault_Exception {
		port.ctrlInit(initialMenus);
	}
}
